[project]
name = "cribbage-engine"
version = "1.1.15"
description = "Shared cribbage game logic"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.12.5"
]
[project.optional-dependencies]
dev = ["pytest>=9.0.2"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["cribbage*"]

[tool.setuptools.package-data]
cribbage = [
    "data/hand_crib_stats.sqlite",
    "players/expert_player/model_meta.json",
    "players/expert_player/pegging_policy.pt",
]
